# "github.com" のリポジトリを指定し、"Plugin" を追加

# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# 統合ユーザインターフェース
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

# # The Silver Searcher 検索
# [[plugins]]
# repo = 'rking/ag.vim'
#
# # インデント カラー化
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
#
# # 行末半角スペースを 視化
# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'
#
# # ステータスライン ビジュアル強化
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# # < http://itchyny.hatenablog.com/entry/20130828/1377653592 >
#
# # コメントON/OFF ショートカットキートグル
# [[plugins]]
# repo = 'tomtom/tcomment_vim'
