# TODO: 動作未検証
# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# !!!: "help jedi" が出るところまで確認済み
# Python開発用プラグイン
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

# TODO: 動作未検証
# 構文チェッカー
[[plugins]]
repo = 'scrooloose/syntastic'
# PEP8に準拠
# FIXME: エラーの為、一旦Kill
# let g:syntastic_python_checkers = ['pyflakes', 'pep8']

# TODO: 動作未検証
# # カラースキーマ
# [[plugins]]
# repo = 'w0ng/vim-hybrid'
# hook_add = '''
#     set background=dark
#     " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#     " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#     au MyAutoCmd VimEnter * nested colorscheme hybrid
#     '''

# 導入予定

# TODOリスト
# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'
