# "github.com" のリポジトリを指定し、"Plugin" を追加
# Last Changed: .

# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# 統合ユーザインターフェース
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
# "unite.vim" 用colorschemeプレビュー
# ":Unite clorcheme" でプレビュー
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
# "unite.vim" 用フォントプレビュー
# ":Unite font" でプレビュー
# FIXME: ↑されない
[[plugins]]
repo = 'ujihisa/unite-font'

# The Silver Searcher 検索
[[plugins]]
repo = 'rking/ag.vim'

# 選択したテキストを'""'、"()"、"[]"などで囲む
[[plugins]]
repo = 'tpope/vim-surround'

# # ファイラー
# ":VimFiler" で起動 # {{{
    # o: 	バッファを縦分割 or ディレクトリ同期
    # O:	別バッファに選択中のディレクトリの中を展開
    # gs:	セーフモード on/off
    # q:	VimFilerを終了
# }}}
[[plugins]]
repo = 'Shougo/vimfiler'

# "vimshell"
[[plugins]]
repo = 'Shougo/vimshell'

# # 関数、クラス、変数、構造体、列挙型、マクロ定義など 一覧表示
# ":TlistOpen" で開始
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# ウィンドウサイズ変更 簡便化
# <Ctrl>e: ウィンドウリサイズ開始
[[plugins]]
repo = 'simeji/winresizer'

# アンドゥ管理
[[plugins]]
repo = 'sjl/gundo.vim'

# インデント カラー化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# ステータスライン ビジュアル強化
[[plugins]]
repo = 'itchyny/lightline.vim'
# < http://itchyny.hatenablog.com/entry/20130828/1377653592 >

# コメントON/OFF ショートカットキートグル
[[plugins]]
repo = 'tomtom/tcomment_vim'

# コマンドラインでEmacsキーバインド
[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

# カーソル移動の拡張
[[plugins]]
repo = 'lokaltog/vim-easymotion'

# "%" で移動を強化（*.htmlのタグなど）
[[plugins]]
repo = 'tmhedberg/matchit'

# 日付のインクリメント・デクリメント
# FIXME: yyyy/mm/dd 形式は対応していない
[[plugins]]
repo = 'tpope/vim-speeddating'

# vim上で計算機機能
# コマンドモードで ":Calc" で計算開始
# "Python" 必要
[[plugins]]
repo = 'gregsexton/VimCalc'

# スネークケースやキャメルケースへの変換
    # ノーマルモードで # {{{
        # crs	"SnakeCase"  → "snake_case"
        # crm	"mixed_case" → "MixedCase"
        # crc	"camel_case" → "camelCase"
        # cru	"upper_case" → "UPPER_CASE"
# }}}
[[plugins]]
repo = 'tpope/vim-abolish'

# タイムスタンプを挿入
#  "Last Cahnged: ." を記入する
# FIXME: 動作せず
[[plugins]]
repo = 'm-scripts/autodate.vim'

# "=" を自動的に " = " にする
[[plugins]]
repo = 'kana/vim-smartchr'

# # "true"/"false"、"yes"、"no"、"on"/"off" などをトグル
# [[plugins]]
# repo = 'toggle.vim'


# git用プラグイン
# 古いので代替したい
[[plugins]]
repo = 'tpope/vim-fugitive'

# 導入予定

# toml
# [[plugins]]
# repo  = 'cespare/vim-toml'
# on_ft = 'toml'

# japanese doc
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'
# on_ft = 'help'

# "ctags" 自動更新
# https://github.com/soramugi/auto-ctags.vim

# テンプレート作成
# [[plugins]]
# repo = 'thinca/vim-template'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >

# テキスト整形
# [[plugins]]
# repo = 'vim-scripts/Align'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >
# < http://nanasi.jp/vim/align.html >

# コピペ 履歴保存
# [[plugins]]
# repo = 'vim-scripts/YankRing.vim'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >

# 削除予定

# # ミニマップ
# [[plugins]]
# # repo = 'mipmip/vim-minimap'
# # todo: 下記の条件分岐は未動作確認
# # if = '''! has ('windows')'''
# repo = "koron/minimap-vim"

# # カーソル位置の "filetype" に切り替え
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']
# [[plugins]] repo = 'shougo/context_filetype.vim'
