# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# Python開発用プラグイン
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

# DONE: エラーの為、一旦Kill
# 構文チェッカー
[[plugins]]
repo = 'sscrooloose/syntastic'
# PEP8に準拠
let g:syntastic_python_checkers = ['pyflakes', 'pep8']

# カラースキーマ
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
    " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
