# "github.com" のリポジトリを指定し、"Plugin" を追加

# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# # 統合ユーザインターフェース
# [[plugins]]
# repo = 'Shougo/unite.vim'
# depends = 'neomru.vim'
# # "unite.vim" 用colorschemeプレビュー
# # TODO: ショートカットキーに登録
# # ":Unite -auto-preview colorscheme" でプレビュー
# [[plugins]]
# repo = 'ujihisa/unite-colorscheme'
# # "unite.vim" 用フォントプレビュー
# # ":Unite font" でプレビュー
# [[plugins]]
# repo = 'ujihisa/unite-font'

# # ファイラー
# [[plugins]]
# repo = 'Shougo/vimfiler'
# # < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >

# # "vimshell"
# [[plugins]]
# repo = 'Shougo/vimshell'

# # 関数、クラス、変数、構造体、列挙型、マクロ定義など 一覧表示
# [[plugins]]
# repo = 'vim-scripts/taglist.vim'

# # "*" で検索時、単語ではなく選択範囲を対象にする
# [[plugins]]
# repo = 'https://github.com/nelstrom/vim-visual-star-search.git'

# # ウィンドウサイズ変更 簡便化
# [[plugins]]
# repo = 'simeji/winresizer'

# "undo" 管理
[[plugins]]
repo = 'sjl/gundo.vim'

# インデント カラー化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# 行末半角スペースを 視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ステータスライン ビジュアル強化
[[plugins]]
repo = 'itchyny/lightline.vim'
# < http://itchyny.hatenablog.com/entry/20130828/1377653592 >

# コメントON/OFF ショートカットキートグル
[[plugins]]
repo = 'tomtom/tcomment_vim'


# Git用プラグイン
# 古いので代替したい
[[plugins]]
repo = 'tpope/vim-fugitive'

# # "()"、 "[]" など 対入力
# Keymapに登録済み
# [[plugins]]
# repo = 'tpope/vim-surround'
# # < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>

# # ミニマップ
# [[plugins]]
# # repo = 'mipmip/vim-minimap'
# # TODO: 下記の条件分岐は未動作確認
# # if = '''! has ('windows')'''
# repo = "koron/minimap-vim"

# # カーソル位置の "filetype" に切り替え
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']
# [[plugins]] repo = 'Shougo/context_filetype.vim'

# 導入予定

# Toml
# [[plugins]]
# repo  = 'cespare/vim-toml'
# on_ft = 'toml'

# Japanese doc
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'
# on_ft = 'help'

# ビジュアル選択部を "*" で検索
# 'nelstrom/vim-visual-star-search

# "ctags" 自動更新
# https://github.com/soramugi/auto-ctags.vim

# テンプレート作成
# [[plugins]]
# repo = 'thinca/vim-template'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >

# テキスト整形
# [[plugins]]
# repo = 'vim-scripts/Align'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >
# < http://nanasi.jp/vim/align.html >

# コピペ 履歴保存
# [[plugins]]
# repo = 'vim-scripts/YankRing.vim'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >
