# TODO: 動作未検証
# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# unite用mru
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

# Python開発用プラグイン
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

# Pythonシンタックスハイライト
[[plugins]]
# repo = 'hdima/python-syntax'
# repo = 'kh3phr3n/python-syntax'
repo = 'pfdevilliers/Pretty-Vim-Python'
on_ft = 'python'

# TODO: 動作未検証
# 構文チェッカー
[[plugins]]
repo = 'scrooloose/syntastic'

# カラースキーマ
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
    " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
    " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
[[plugins]]
repo = 'vim-scripts/twilight'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme hybrid
    '''
