# "github.com" のリポジトリを指定し、"Plugin" を追加
# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# 統合ユーザインターフェース
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
# "unite.vim" 用colorschemeプレビュー
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
# TODO: ショートカットキーに登録
# ":Unite -auto-preview colorscheme" でプレビュー

# "unite.vim" 用フォントプレビュー
[[plugins]]
repo = 'ujihisa/unite-font'
# ":Unite font" でプレビュー

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neocomplcache.vim'

# カーソル位置のコンテキストに合わせて "filetype" を切り替え
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]] repo = 'Shougo/context_filetype.vim'

# TODO: 動作未検証
# Git用プラグイン
[[plugins]]
repo = 'tpope/vim-fugitive'

# コメントのON/OFFをショートカットキーでトグル
[[plugins]]
repo = 'tomtom/tcomment_vim'

# インデントをカラー化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# 行末の半角スペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ステータスラインのビジュアルを強化
[[plugins]]
repo = 'itchyny/lightline.vim'
# <http://itchyny.hatenablog.com/entry/20130828/1377653592>

# ミニマップ
[[plugins]]
repo = 'mipmip/vim-minimap'


# 導入予定

# テンプレート作成
# [[plugins]]
# repo = 'thinca/vim-template'
# <http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>

# ファイラー
[[plugins]]
repo = 'Shougo/vimfiler'
# <http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>

# "()" 、 "[]" などの操作
[[plugins]]
repo = 'tpope/vim-surround'
# <http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>

# テキスト整形
# [[plugins]]
# repo = 'vim-scripts/Align'
# <http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>
# <http://nanasi.jp/vim/align.html>

# コピペの履歴を保存
# [[plugins]]
# repo = 'vim-scripts/YankRing.vim'
# <http://lambdalisue.hatenablog.com/entry/2013/06/23/071344>

# Undu管理
# gundo.vim

# Toml
# [[plugins]]
# repo  = 'cespare/vim-toml'
# on_ft = 'toml'

# Markdown
# [[plugins]]
# repo = 'rcmdnk/vim-markdown'
# on_ft = ['markdown','mkd']
# hook_add = '''
#   let g:vim_markdown_frontmatter = 1
#   let g:vim_markdown_math = 1
# '''

# Japanese doc
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'
# on_ft = 'help'
