# Created:     2018/12/19 08:49:17.
# Last Change: 2020/11/08 21:39:05.

# REF:
    # hook_add         プラグイン追加後
    # hook_source      プラグイン読込前
    # hook_post_source プラグイン読込後

# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# Grep
    # The Silver Searcher
[[plugins]]
repo = 'rking/ag.vim'
    # The Platinum Searcher
[[plugins]]
repo = 'nazo/pt.vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
    # 追加、削除マーカ表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
    # "git log" を強化
    # :Agit 強化版 "git log" 実行
[[plugins]]
repo = 'cohama/agit.vim'
    # "gitk" 機能追加
        # :Gitv: 機能追加版 "gitk" 実行
[[plugins]]
repo = 'gregsexton/gitv'
depends = ['vim-fugitive']
    # コミットログ入力強化
[[plugins]]
repo = 'rhysd/committia.vim'

# Diff
    # :DirDiff A B: AとBを比較
[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

# LSP(Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# Ctags
    # どの関数内か表示
[[plugins]]
repo = 'majutsushi/tagbar'

# ファイラ
[[plugins]]
repo = 'Shougo/defx.nvim'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']

# ステータスライン ビジュアル強化
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive', 'tagbar']
# < http://itchyny.hatenablog.com/entry/20130828/1377653592 >
# アイコン表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# カーソル位置の "filetype" を自動切替
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# コピペ履歴
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_source = '''  " {{{
    nmap p        <Plug>(yankround-p)
    xmap p        <Plug>(yankround-p)
    nmap P        <Plug>(yankround-P)
    nmap gp       <Plug>(yankround-gp)
    xmap gp       <Plug>(yankround-gp)
    nmap gP       <Plug>(yankround-gP)
    nmap <S-Up>   <Plug>(yankround-prev)
    nmap <S-Down> <Plug>(yankround-next)
    " コマンドライン内の設定
	  cmap <C-r>    <Plug>(yankround-insert-register)
	  cmap <C-y>    <Plug>(yankround-pop)
'''  # }}}

# Undo履歴
[[plugins]]
repo = 'sjl/gundo.vim'

# 置換強化
[[plugins]]
repo = 'osyo-manga/vim-over'

# 置換プレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# キーバインド衝突確認
[[plugins]]
repo = 'lukhio/vim-mapping-conflicts'

# チートシート表示
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# 辞書
[[plugins]]
repo = 'thinca/vim-ref'

# 翻訳
[[plugins]]
repo = 'daisuzu/translategoogle.vim'
[[plugins]]
repo = 'skanehira/translate.vim'

# 起動画面機能強化
[[plugins]]
repo = 'mhinz/vim-startify'

# ウィンドゥリサイズ
[[plugins]]
repo = 'simeji/winresizer'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# カーソル機能強化
[[plugins]]
repo = 'lokaltog/vim-easymotion'

# コメント ON/OFFトグル
[[plugins]]
repo = 'tomtom/tcomment_vim'

# テキスト整形
[[plugins]]
repo = 'junegunn/vim-easy-align'

# 閉じ括弧入力補完
[[plugins]]
repo = 'cohama/lexima.vim'

# "%" 移動機能強化
    # *.htmlのタグなど
[[plugins]]
repo = 'tmhedberg/matchit'

# 選択テキストを'""'、"()"、"[]"などで囲む
[[plugins]]
repo = 'tpope/vim-surround'

# vim-surround をドットコマンドに対応させる
[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1

# スネークケース、キャメルケースへ変換
[[plugins]]
repo = 'tpope/vim-abolish'

# "=" などの入力を拡張
    # " = " にする等
[[plugins]]
repo = 'kana/vim-smartchr'

# # タイムスタンプ 挿入
# [[plugins]]
# repo = 'vim-scripts/autodate.vim'

# 日付のインクリメント・デクリメント
    # FIXME: yyyy/mm/dd 形式は対応していない
[[plugins]]
repo = 'tpope/vim-speeddating'

# "TagList" を開く
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# "*.toml" シンタックスハイライト
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# インデント 強調
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# マーク ビジュアル化
[[plugins]]
repo = 'jacquesbh/vim-showmarks'

# テーブル作成
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# カレンダ
[[plugins]]
repo = 'itchyny/calendar.vim'

# 計算機
    # :Calc: で計算開始
[[plugins]]
repo = 'gregsexton/VimCalc'
if = "!has('python')"

# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'
if = "has('gui_running')"
# "iceberg" が適応されなくなったのでキル
# hook_add = '''
#    set termguicolors
#    set background=dark
#    au MyAutoCmd VimEnter * nested colorscheme iceberg
#    au MyAutoCmd VimEnter * highlight Visual ctermbg=216
# '''

# 日本語ヘルプ
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# カラースキーム ランダム設定
# [[plugins]]
# repo = 'shinshin86/twc.vim'

# JOKE
# [[plugins]]
# repo = 'wordijp/kuririn-no-kotoka.vim'

# DISCON:
# # 天気予報
# [[plugins]]
# repo = 'skanehira/weather.vim'

# # 乗換え案内
# [[plugins]]
# repo = 'skanehira/train.vim'
