# Created:     2018/12/19 08:50:01
# Last Change: 2023/03/18 16:25:20.

# ---------------------------------------------------------------------------
#  参考
# ---------------------------------------------------------------------------
# < REF: https://leico.github.io/TechnicalNote/VimR/VimR-dein-toml >  # {{{

# on_i
# 1: インサートモードに入った時に読込み
# on_ft
# 指定したファイルタイプの時に読込み
# on_path
# バッファ名が一致した時に読込み
# .*を指定すると何かのファイルを開いた時に読込まれる
# filer などの"Plugin" で使うと便利
# on_source
# 記載された"Plugin" が読み込まれた後に読込み
# on_cmd
# コマンドが実行された時に読込み
# 主に ['Unite', 'UniteResume'] のような"Plugin" のコマンドを指定す
# on_map
# on_cmdのマッピング版、['<Plug>(neosnippet_expand_or_jump)'] のように指定
# depends
# "Plugin" 間で依存性がある場合に使用
# 記述しても自動的にインストールされない点は neobundle.vim 挙動が違う
# if
# has("nvim") のように条件に一致した場合のみ読込み

# hook の種類
# hook の名前      実行タイミング          lazy OFF lazy ON
# hook_add         dein.vim に追加された時 OK       OK
# hook_source      読込み直前              NG       OK
# hook_post_source 読込み直後              NG       OK
# hook_post_update 更新直後                OK       OK
# }}}

# タイムスタンプ 挿入
[[plugins]]
repo             = 'vim-scripts/autodate.vim'

# チートシート表示
[[plugins]]
repo             = 'reireias/vim-cheatsheet'
on_cmd           = ['Cheat']

# ウィンドウ リサイズ
[[plugins]]
repo             = 'simeji/winresizer'
# on_cmd           = ['***']

# テキスト整形
[[plugins]]
repo             = 'junegunn/vim-easy-align'
on_map           = ['<Plug>(EasyAlign)']

# Undo履歴
[[plugins]]
repo             = 'sjl/gundo.vim'
on_cmd           = ['GundoToggle']

# 置換プレビュー
[[plugins]]
repo             = 'osyo-manga/vim-over'
on_cmd           = ['OverCommandLine']

# "*.toml" シンタックスハイライト
[[plugins]]
repo             = 'cespare/vim-toml'
on_ft            = ['toml']

# "*.fish" シンタックスハイライト
[[plugins]]
repo             = 'dag/vim-fish'
on_ft            = ['fish']

# Tagbar
[[plugins]]
repo             = 'majutsushi/tagbar'
on_cmd           = ['TagbarToggle']

# TagList
[[plugins]]
repo             = 'vim-scripts/taglist.vim'
on_cmd           = ['TlistOpen']

# CtrlP
[[plugins]]
repo             = 'ctrlpvim/ctrlp.vim'
on_map           = ['<C-l>']

# fzf
[[plugins]]
repo             = 'junegunn/fzf'
build            = './install --bin'
merged           = '0'
on_cmd           = ['FZF']
[[plugins]]
repo             = 'junegunn/fzf.vim'
depends          = ['fzf']
# hook_add = '''  " {{{
#     command! -bang -nargs=* Rg
#                 \ call fzf#vim#grep(
#                 \   'rg --hidden --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
#                 \   <bang>0 ? fzf#vim#with_preview('up:60%')
#                 \           : fzf#vim#with_preview('right:50%:hidden', '?'),
#                 \   <bang>0)
#     command! -bang -nargs=* Rgs
#                 \ call fzf#vim#grep(
#                 \   'rg --hidden --column --line-number --no-heading --color=always --smart-case --encoding Shift_JIS '.shellescape(<q-args>), 1,
#                 \   <bang>0 ? fzf#vim#with_preview('up:60%')
#                 \           : fzf#vim#with_preview('right:50%:hidden', '?'),
#                 \   <bang>0)
#     command! -bang -nargs=* Ag
#                 \ call fzf#vim#grep(
#                 \   'ag --hidden --column --color --ignore .git '.shellescape(<q-args>), 0,
#                 \   <bang>0 ? fzf#vim#with_preview('up:60%')
#                 \           : fzf#vim#with_preview('right:50%', '?'),
#                 \   <bang>0)
# '''  # }}}

# Git
[[plugins]]
repo             = 'tpope/vim-fugitive'
hook_post_source = '''
    echom 'fugitive is loaded'
'''
# 左に差分を表示
[[plugins]]
repo             = 'cohama/agit.vim'
on_cmd           = ['Agit']

# ALE
[[plugins]]
repo             = 'w0rp/ale'
if               = "has('job') && has('channel') && has('timers')"
[[plugins]]
repo             = 'scrooloose/syntastic'
if               = "!has('job') || !has('channel') || !has('timers')"

# LSP(Language Server Protocol)
[[plugins]]
repo             = 'prabirshrestha/vim-lsp'
on_map           = ['<F6>']
[[plugins]]
repo             = 'mattn/vim-lsp-settings'
on_map           = ['<F6>']
[[plugins]]
repo             = 'mattn/vim-lsp-icons'
on_map           = ['<F6>']

# Vim 起動時間計測
[[plugins]]
repo             = 'dstein64/vim-startuptime'
on_cmd           = ['StartupTime']
[[plugins]]
repo             = 'mattn/benchvimrc-vim'
on_cmd           = ['BenchVimrc']

# 日本語ヘルプ
# MEMO: "KaoriYa" 以外の環境で必要か確認
# Windows NeoVim 必要
[[plugins]]
repo             = 'vim-jp/vimdoc-ja'
