# Created:     2018/12/19 08:49:17.
# Last Change: 2018/12/19 11:14:40.

# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'
if = "has('gui_running')"
hook_add = '''
    set termguicolors
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme iceberg
    au MyAutoCmd VimEnter * highlight Visual ctermbg=216
'''

