# Created:     2018/12/19 08:49:17.
# Last Change: 2018/12/27 10:48:51.

# MEMO:
# hook_add         プラグイン追加後
# hook_source      プラグイン読込み前
# hook_post_source プラグイン読込み後

# "dein.vim" 本体
[[plugins]]
repo = 'Shougo/dein.vim'

# コピペ履歴保存
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_source = '''  " {{{
    nmap p <Plug>(yankround-p)
    xmap p <Plug>(yankround-p)
    nmap P <Plug>(yankround-P)
    nmap gp <Plug>(yankround-gp)
    xmap gp <Plug>(yankround-gp)
    nmap gP <Plug>(yankround-gP)
    nmap <C-p> <Plug>(yankround-prev)
    nmap <C-n> <Plug>(yankround-next)
'''  # }}}

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'
# 追加、削除マーカ表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
# "git log" を強化
    # :Agit 強化版 "git log" 実行
[[plugins]]
repo = 'cohama/agit.vim'
# "gitk" 機能追加
    # :Gitv: 機能追加版 "gitk" 実行
[[plugins]]
repo = 'gregsexton/gitv'
depends = ['vim-fugitive']
# コミットログ入力強化
[[plugins]]
repo = 'rhysd/committia.vim'

# Grep
# The Silver Searcher
[[plugins]]
repo = 'rking/ag.vim'
# The Platinum Searcher
[[plugins]]
repo = 'nazo/pt.vim'

# Diff
    # :DirDiff A B: AとBを比較
[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

# Ctags
# どの関数内か表示
[[plugins]]
repo = 'majutsushi/tagbar'

# キーバインド衝突確認
[[plugins]]
repo = 'lukhio/vim-mapping-conflicts'

# Undo履歴
[[plugins]]
repo = 'sjl/gundo.vim'

# 置換強化
[[plugins]]
repo = 'osyo-manga/vim-over'

# チートシート表示
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# 辞書
[[plugins]]
repo = 'thinca/vim-ref'
# 翻訳
[[plugins]]
repo = 'daisuzu/translategoogle.vim'

# ファイラ
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']
# ステータスライン ビジュアル強化
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive', 'tagbar']
# < http://itchyny.hatenablog.com/entry/20130828/1377653592 >
# アイコン表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ウィンドウリサイズ
[[plugins]]
repo = 'simeji/winresizer'

# 起動画面機能強化
[[plugins]]
repo = 'mhinz/vim-startify'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# カーソル機能強化
[[plugins]]
repo = 'lokaltog/vim-easymotion'

# コメント ON/OFFトグル
[[plugins]]
repo = 'tomtom/tcomment_vim'

# テキスト整形
# 対象行を選択し "ga" -> "整形対象" ->  "デリミタ" を入力
[[plugins]]
repo = 'junegunn/vim-easy-align'

# 閉じ括弧入力補完
[[plugins]]
repo = 'cohama/lexima.vim'

# "%" 移動機能強化
    # *.htmlのタグなど
[[plugins]]
repo = 'tmhedberg/matchit'

# 選択テキストを'""'、"()"、"[]"などで囲む
[[plugins]]
repo = 'tpope/vim-surround'

# スネークケース、キャメルケースへ変換  # {{{
    # ノーマルモードで
        # crs: "SnakeCase"  → "snake_case"
        # crm: "mixed_case" → "MixedCase"
        # crc: "camel_case" → "camelCase"
        # cru: "upper_case" → "UPPER_CASE"
# }}}
[[plugins]]
repo = 'tpope/vim-abolish'

# "=" を自動的に " = " にする
[[plugins]]
repo = 'kana/vim-smartchr'

# タイムスタンプ 挿入
[[plugins]]
repo = 'vim-scripts/autodate.vim'

# 日付のインクリメント・デクリメント
    # FIXME: yyyy/mm/dd 形式は対応していない
[[plugins]]
repo = 'tpope/vim-speeddating'

# カーソル位置の "filetype" を自動切替
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
# カーソル位置の "filetype" を自動判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# # 関数、クラス、変数、構造体、列挙型、マクロ定義など 一覧表示
    # ":TlistOpen" で開始
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# "*.toml" シンタックスハイライト
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# インデント カラー化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# マーク ビジュアル化
[[plugins]]
repo = 'jacquesbh/vim-showmarks'

# テーブル作成
# ":TableModeToggle" で開始
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# カレンダ
[[plugins]]
repo = 'itchyny/calendar.vim'

# 計算機
    # :Calc: で計算開始
    # "Python" 必要
[[plugins]]
repo = 'gregsexton/VimCalc'
if = "!has('python')"

# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'
if = "has('gui_running')"
hook_add = '''
    set termguicolors
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme iceberg
    au MyAutoCmd VimEnter * highlight Visual ctermbg=216
'''
[[plugins]]
repo = 'shinshin86/twc.vim'

# JOKE
[[plugins]]
repo = 'wordijp/kuririn-no-kotoka.vim'

