# Created:     2018/12/19 08:49:17.
# Last Change: 2023/03/18 16:44:28.

# ---------------------------------------------------------------------------
#  参考
# ---------------------------------------------------------------------------
# < REF: https://leico.github.io/TechnicalNote/VimR/VimR-dein-toml >  # {{{

# on_i
# 1: インサートモードに入った時に読込み
# on_ft
# 指定したファイルタイプの時に読込み
# on_path
# バッファ名が一致した時に読込み
# .*を指定すると何かのファイルを開いた時に読込まれる
# filer などの"Plugin" で使うと便利
# on_source
# 記載された"Plugin" が読み込まれた後に読込み
# on_cmd
# コマンドが実行された時に読込み
# 主に ['Unite', 'UniteResume'] のような"Plugin" のコマンドを指定す
# on_map
# on_cmdのマッピング版、['<Plug>(neosnippet_expand_or_jump)'] のように指定
# depends
# "Plugin" 間で依存性がある場合に使用
# 記述しても自動的にインストールされない点は neobundle.vim 挙動が違う
# if
# has("nvim") のように条件に一致した場合のみ読込み

# hook の種類
# hook の名前      実行タイミング          lazy OFF lazy ON
# hook_add         dein.vim に追加された時 OK       OK
# hook_source      読込み直前              NG       OK
# hook_post_source 読込み直後              NG       OK
# hook_post_update 更新直後                OK       OK
# }}}

# "dein.vim" 本体
[[plugins]]
repo        = 'Shougo/dein.vim'

# -----------------------------------------------------------------------------
# lazy から移管
# -----------------------------------------------------------------------------
# コピペ履歴
[[plugins]]
repo        = 'LeafCage/yankround.vim'

# カーソル機能強化
[[plugins]]
repo        = 'lokaltog/vim-easymotion'
on_map      = [',']

# コメントアウト トグル
[[plugins]]
repo        = 'tomtom/tcomment_vim'
on_map      = ['<C-=>']

# 記述の追加、削除マーカ表示
[[plugins]]
repo        = 'airblade/vim-gitgutter'
# -----------------------------------------------------------------------------

# 起動画面機能強化
[[plugins]]
repo        = 'mhinz/vim-startify'

# 自動補完
[[plugins]]
repo        = 'neoclide/coc.nvim'
rev         = 'release'
on_i        = 1
merged      = '0'
hook_source = 'call coil398#init#coc#hook_source()'

# スニペット入力
[[plugins]]
repo        = 'Shougo/neosnippet'
depends     = ['neosnippet-snippets', 'context_filetype.vim']
on_i        = 1
on_ft       = ['snippet']
[[plugins]]
repo        = 'Shougo/neosnippet-snippets'

# ステータスライン 強化
[[plugins]]
repo        = 'itchyny/lightline.vim'
depends     = ['vim-fugitive', 'tagbar']
# < REF: http://itchyny.hatenablog.com/entry/20130828/1377653592 >
# ステータスライン用 デビコン
[[plugins]]
repo        = 'ryanoasis/vim-devicons'

# インデント 強調
[[plugins]]
repo        = 'nathanaelkane/vim-indent-guides'

# 選択テキストを'""'、"()"、"[]"などで囲む
[[plugins]]
repo        = 'tpope/vim-surround'

# "=" などの入力を拡張
    # " = " にする等
[[plugins]]
repo        = 'kana/vim-smartchr'

# 閉じ括弧入力補完
[[plugins]]
repo        = 'cohama/lexima.vim'

# テーブル作成
[[plugins]]
repo        = 'dhruvasagar/vim-table-mode'

# スネークケース、キャメルケースへ変換
[[plugins]]
repo        = 'tpope/vim-abolish'

# カーソル位置の "filetype" を自動切替
[[plugins]]
repo        = 'osyo-manga/vim-precious'
depends     = ['context_filetype.vim']
[[plugins]]
repo        = 'Shougo/context_filetype.vim'
