# Created:     2018/12/19 08:50:47
# Last Change: 2021/03/05 11:41:02.

# Python用プラグイン
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# 補完
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

# シンタックスハイライト
[[plugins]]
repo = 'pfdevilliers/Pretty-Vim-Python'
on_ft = ['python']

# コード整形
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

# 自動折りたたみ
# [[plugins]]
# repo = 'vim-scripts/python_fold'
# on_ft = ['python']
