# Created:     2018/03/07 21:59:29
# Last Change: 2018/12/20 11:17:09.

# 文章校正
# [[plugins]]  # {{{
# repo = 'rinx/yj-proofreading.vim'
# depends = ['mattn/webapi-vim']
# [[plugins]]
# repo = 'mattn/webapi-vim'
# }}}

# ファイラ
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']
# ,sp: カレントディレクトリ以下を検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
if = "!has('nvim')"
# :VimFiler で起動 # {{{
    # o: バッファを縦分割 or ディレクトリ同期
    # O: 別バッファに選択中のディレクトリの中を展開
    # gs: セーフモード ON/OFF
    # q: 終了
# }}}
[[plugins]]
repo = 'Shougo/vimfiler'

# ステータスライン ビジュアル強化
[[plugins]]
repo = 'itchyny/lightline.vim'
# depends = ['vim-fugitive', 'majutsushi/tagbar']
depends = ['vim-fugitive', 'tagbar']
# < http://itchyny.hatenablog.com/entry/20130828/1377653592 >
# アイコン表示
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# どの関数中か表示
[[plugins]]
repo = 'majutsushi/tagbar'

# ウィンドウリサイズ
[[plugins]]
repo = 'simeji/winresizer'

# 起動画面機能強化
[[plugins]]
repo = 'mhinz/vim-startify'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# カーソル機能強化
[[plugins]]
repo = 'lokaltog/vim-easymotion'

# コメント ON/OFFトグル
[[plugins]]
repo = 'tomtom/tcomment_vim'

# テキスト整形
# 対象行を選択し "ga" -> "整形対象" ->  "デリミタ" を入力
[[plugins]]
repo = 'junegunn/vim-easy-align'

# 閉じ括弧入力補完
[[plugins]]
repo = 'cohama/lexima.vim'

# "%" 移動機能強化
    # *.htmlのタグなど
[[plugins]]
repo = 'tmhedberg/matchit'

# 選択テキストを'""'、"()"、"[]"などで囲む
[[plugins]]
repo = 'tpope/vim-surround'

# スネークケース、キャメルケースへ変換  # {{{
    # ノーマルモードで
        # crs: "SnakeCase"  → "snake_case"
        # crm: "mixed_case" → "MixedCase"
        # crc: "camel_case" → "camelCase"
        # cru: "upper_case" → "UPPER_CASE"
# }}}
[[plugins]]
repo = 'tpope/vim-abolish'

# "=" を自動的に " = " にする
[[plugins]]
repo = 'kana/vim-smartchr'

# タイムスタンプ 挿入
[[plugins]]
repo = 'vim-scripts/autodate.vim'

# 日付のインクリメント・デクリメント
    # FIXME: yyyy/mm/dd 形式は対応していない
[[plugins]]
repo = 'tpope/vim-speeddating'

# カーソル位置の "filetype" を自動切替
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
# カーソル位置の "filetype" を自動判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# # 関数、クラス、変数、構造体、列挙型、マクロ定義など 一覧表示
    # ":TlistOpen" で開始
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# "*.toml" シンタックスハイライト
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# インデント カラー化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# マーク ビジュアル化
[[plugins]]
repo = 'jacquesbh/vim-showmarks'

# 計算機
    # :Calc: で計算開始
    # "Python" 必要
[[plugins]]
repo = 'gregsexton/VimCalc'
if = "!has('python')"

# カレンダ
[[plugins]]
repo = 'itchyny/calendar.vim'

# # "true"/"false"、"yes"、"no"、"on"/"off" などをトグル
# [[plugins]]
# repo = 'toggle.vim'

# ---------------------------------------------------------------------------
# 動作確認中 新規導入プラグイン
# ---------------------------------------------------------------------------
# テーブル作成
# ":TableModeToggle" で開始
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# ---------------------------------------------------------------------------
# 導入予定
# ---------------------------------------------------------------------------
# {{{
# japanese doc
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'
# on_ft = ['help']

# "ctags" 自動更新
# https://github.com/soramugi/auto-ctags.vim

# テンプレート作成
# [[plugins]]
# repo = 'thinca/vim-template'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >
# }}}

# ---------------------------------------------------------------------------
# 削除予定
# ---------------------------------------------------------------------------
# "VimShell"
# # ",s: :VimShell" で起動
# [[plugins]]
# repo = 'Shougo/vimshell'
# if = "!has('nvim')"

# MEMO: ↓コピペができないのでKILL
# # コマンドラインで "Emacs" キーバインド
# [[plugins]]
# repo = 'houtsnip/vim-emacscommandline'

# GAME
# [[plugins]]
# repo = 'rbtnn/game_engine.vim'
# [[plugins]]
# repo = 'rbtnn/pipe.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/mario.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/puyo.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/reversi.vim'
# depends = ['game_engine']

