# Created:     2018/12/18 08:26:34
# Last Change: 2018/12/18 08:28:08.

# Python用プラグイン
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# シンタックスハイライト
[[plugins]]
repo = 'pfdevilliers/Pretty-Vim-Python'
on_ft = ['python']

# 自動折りたたみ
# [[plugins]]
# repo = 'vim-scripts/python_fold'
# on_ft = ['python']

