# Created:     2018/03/07 21:59:29
# Last Change: 2019/07/01 21:36:47.

[[plugins]]
repo = 'Shougo/vimfiler'
# :VimFiler で起動 # {{{
    # o: バッファを縦分割 or ディレクトリ同期
    # O: 別バッファに選択中のディレクトリの中を展開
    # gs: セーフモード ON/OFF
    # q: 終了
# }}}
