# Created:     2018/03/07 21:59:29
# Last Change: 2018/12/27 10:20:24.

# 入力補完
# 最新
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
depends = ['roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc']
hook_add = '''  " {{{
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
'''  # }}}
on_event = ['InsertCharPre']
hook_source = '''  " {{{
    inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
    inoremap <expr><C-l> deoplete#complete_common_string()
    inoremap <expr><C-i> deoplete#complete_common_string()
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
                \ neosnippet#expandable_or_jumpable() ?
                \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"

    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10000
'''  # }}}
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# :VimFiler で起動 # {{{
    # o: バッファを縦分割 or ディレクトリ同期
    # O: 別バッファに選択中のディレクトリの中を展開
    # gs: セーフモード ON/OFF
    # q: 終了
# }}}
[[plugins]]
repo = 'Shougo/vimfiler'

# 移管済み  " {{{
# # "true"/"false"、"yes"、"no"、"on"/"off" などをトグル
# [[plugins]]
# repo = 'toggle.vim'

# ---------------------------------------------------------------------------
# 動作確認中 新規導入プラグイン
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# 導入予定
# ---------------------------------------------------------------------------
# {{{
# japanese doc
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'
# on_ft = ['help']

# "ctags" 自動更新
# https://github.com/soramugi/auto-ctags.vim

# テンプレート作成
# [[plugins]]
# repo = 'thinca/vim-template'
# < http://lambdalisue.hatenablog.com/entry/2013/06/23/071344 >
# }}}

# ---------------------------------------------------------------------------
# 削除予定
# ---------------------------------------------------------------------------
# 文章校正
# [[plugins]]  # {{{
# repo = 'rinx/yj-proofreading.vim'
# depends = ['mattn/webapi-vim']
# [[plugins]]
# repo = 'mattn/webapi-vim'
# }}}

# "VimShell"
# # ",s: :VimShell" で起動
# [[plugins]]
# repo = 'Shougo/vimshell'
# if = "!has('nvim')"

# MEMO: ↓コピペができないのでKILL
# # コマンドラインで "Emacs" キーバインド
# [[plugins]]
# repo = 'houtsnip/vim-emacscommandline'

# GAME
# [[plugins]]
# repo = 'rbtnn/game_engine.vim'
# [[plugins]]
# repo = 'rbtnn/pipe.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/mario.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/puyo.vim'
# depends = ['game_engine']
# [[plugins]]
# repo = 'rbtnn/reversi.vim'
# depends = ['game_engine']
# }}}

