# Created:     2018/03/07 21:59:29
# Last Change: 2018/12/21 07:41:26.
# TODO: "hook_post_source"、"hook_post_source" を "*.vim" に移管

# 統合ユーザインターフェース
[[plugins]]
repo = 'Shougo/unite.vim'
# TODO: "Denite" 動作テスト完了後に
# ↓を復帰して "Unite" 使用完了
# if = "!has('python3')"
depends = ['neomru.vim']

# 入力補完
# 2番目に新しい
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = ['context_filetype.vim']
if = "!has('python3') && has('lua')"
# MEMO: この "hook_source" は条件分岐の為 "*.vim" に移管しない
hook_source = '''
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-l> neocomplete#complete_common_string()
inoremap <expr><C-i> neocomplete#complete_common_string()
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
            \ neosnippet#expandable_or_jumpable() ?
            \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
# on_i = 1
# 最古
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
if = "!has('python3') && !has('lua')"
on_i = 1
# }}}

# 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# FIXME: 起動時エラーのためKILL
# [[plugins]]
# repo = 'Shougo/unite-outline'
# depends = 'unite.vim'
# hook_add = 'source ~/.vim/userautoload/plugins/plugins-unite-outline.vim'
# [[plugins]]
# repo = 'tsukkee/unite-tag.git'

# MEMO: dein_python.toml に移管
# # Python用プラグイン
# [[plugins]]  # {{{
# repo = 'davidhalter/jedi-vim'
# on_ft = ['python']
# # Pythonシンタックスハイライト
# [[plugins]]
# repo = 'pfdevilliers/Pretty-Vim-Python'
# on_ft = ['python']
# # Python自動折りたたみ
# # [[plugins]]
# # repo = 'vim-scripts/python_fold'
# # on_ft = ['python']
# }}}

# Markdown
# # シンタックスハイライト  # {{{
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# on_ft = ['markdown','mkd']
# hook_add = '''
#     let g:vim_markdown_folding_disabled = 1
#     let g:vim_markdown_auto_insert_bullets = 0
#     let g:vim_markdown_new_list_item_indent = 0
# '''  # }}}

# ---------------------------------------------------------------------------
# TODO: 動作確認
# ---------------------------------------------------------------------------
# {{{
# # カラーコード プレビュー
# [[plugins]]
# repo = 'gorodinskiy/vim-coloresque'

# # Arduino開発用プラグイン
# [[plugins]]
# repo = "platformio/platformio"
# on_ft = ["arduino"]
# # Arduinoシンタックスハイライト
# [[plugins]]
# repo = "sudar/vim-arduino-syntax"
# on_ft = ["arduino"]
# }}}

# ---------------------------------------------------------------------------
# TODO: 導入予定
# ---------------------------------------------------------------------------

