
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew cairo
brew cmake
brew cscope
brew ctags
brew czmq
brew dcraw
brew eigen
brew ffmpeg
brew fish
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew fzf
brew gcc
brew gdbm
brew gettext
brew git
brew glib
brew gmp
brew gobject-introspection
brew graphite2
brew harfbuzz
brew icu4c
brew ilmbase
brew imagemagick
brew isl
brew jasper
brew jemalloc
brew jpeg
brew lame
brew libffi
brew libmpc
brew libpng
brew libsodium
brew libtermkey
brew libtiff
brew libtool
brew libuv
brew libvterm
brew libyaml
brew little-cms
brew little-cms2
brew lua
brew luajit
brew macvim
brew mas
brew mpfr
brew msgpack
brew neovim
brew numpy
brew open-jtalk
brew opencv
brew openexr
brew openssl
brew pandoc
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew pixman
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python
brew python@2
brew readline
brew ripgrep
brew ruby
brew sphinx-doc
brew sqlite
brew tbb
brew the_silver_searcher
brew tree
brew ufraw
brew unibilium
brew vim --with-lua
brew x264
brew xvid
brew xz
brew zbar
brew zeromq
brew zsh
brew zsh-completions

tap homebrew/bundle

tap caskroom/cask
cask atom
cask iterm2
cask karabiner-elements
cask vagrant
cask virtualbox
cask xquartz

tap argon/mas

tap neovim/neovim

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty

# App Store applications
appstore 529456740 CheatSheet (1.0.3)
appstore 563362017 CloudClip Manager (1.3.5)
appstore 807814068 ColorQuest (1.0)
appstore 672206759 Disk Diag (1.4)
appstore 784466108 ExifPurge (1.0)
appstore 554503804 Face4Pass (1.21)
appstore 412448059 ForkLift (2.6.6)
appstore 484829041 iBoostUp (5.99)
appstore 408981434 iMovie (10.1.9)
appstore 409183694 Keynote (8.0.1)
appstore 472226235 LanScan (6.0.1)
appstore 1139055360 MarkPy (1.1)
appstore 689992800 MemoryKeeper (1.3)
appstore 715768417 Microsoft Remote Desktop (8.0.27325)
appstore 571478381 MouseX (1.1)
appstore 409203825 Numbers (5.0.1)
appstore 823766827 OneDrive (18.065.0329)
appstore 409201541 Pages (7.0.1)
appstore 531817541 Pingo HD (1.0)
appstore 568494494 Pocket (1.7.8)
appstore 483820530 QR Journal (1.6)
appstore 897118787 Shazam (1.2.5)
appstore 425955336 Skitch (2.8.1)
appstore 484868989 System Lens (2.61)
appstore 425424353 The Unarchiver (3.11.5)
appstore 557168941 Tweetbot (2.5.4)
appstore 610341008 Wimoweh (1.1.60)
appstore 582840059 Wireless Signal (2.1)
appstore 497799835 Xcode (9.3.1)
